### ISSUE TITLE
You never accepted the Pull request

### ISSUE THREAD

**Issue by jewpaltz** [rizzoct/Fitness-App#2]
https://github.com/rizzoct/Fitness-App/blob/8ac6e84ae8932245689cdddbacd61c6faf7fea1f/index.html#L63

You still have non-working code here.

**Comment by rizzoct** [comment]
Sorry, let me go do that, I didn't know thats how it worked.

**Comment by rizzoct** [comment]
Should I merge it? Also, I was wondering if maybe we can meet regarding my
project just so I can ask you a few questions and get caught up. Thanks.

**Comment by jewpaltz** [comment]
B”H

Yup!
